import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from 'components/app.layout'
import { Box, Button, Container, Heading, HStack, Image, Stack } from '@chakra-ui/react'
import { useState } from 'react'
import { RiSaveLine, RiShoppingBagLine } from 'react-icons/ri'

const inter = Inter({ subsets: ['latin'] })

const Page = () => {
  const [activeButtonId, setActiveButtonId] = useState('')

  const handleButtonClick = (buttonId: string) => {
    setActiveButtonId(buttonId)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="100%" h="100%">
        <Stack h="100%" align="center" justify="center">
          <Box pos="relative" w="100%" h="100%">
            <Image
              src="/preview.png"
              alt="Example image"
              maxW="100%"
              maxH="100%"
              boxSize="720px"
              objectFit="contain"
              m="auto"
              userSelect="none"
              pointerEvents="none"
            />
          </Box>

          <HStack py={{ base: '', md: '12' }} pos="fixed" bottom="0">
            <Button leftIcon={<RiSaveLine size="24px" />} textTransform="uppercase">
              Save Design
            </Button>
            <Button leftIcon={<RiShoppingBagLine size="24px" />} size="lg" variant="primary" textTransform="uppercase">
              Add to Cart
            </Button>
          </HStack>
        </Stack>
      </Container>
    </>
  )
}

Page.Layout = Layout
export default Page
